version: "3.9"

services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/scrapper
    command:
      [
        "bash",
        "-c",
        "scrapy crawl hs-rheinwaal && touch /app/scraper_done.flag",
      ]
    volumes:
      - ./app:/app

  processor:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/helper
    command:
      [
        "bash",
        "-c",
        "while [ ! -f /app/scraper_done.flag ]; do sleep 60; done && python data_preprocesser.py && touch /app/processor_done.flag",
      ]
    depends_on:
      - scraper
    volumes:
      - ./app:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/frontend
    command:
      [
        "bash",
        "-c",
        "while [ ! -f /app/processor_done.flag ]; do sleep 60; done && streamlit run frontend.py",
      ]
    ports:
      - "8501:8501"
    depends_on:
      - processor
    volumes:
      - ./app:/app
